### ISSUE TITLE
sonarwhal scanner reports 35 errors on https://sonarwhal.com/scanner

### ISSUE THREAD

**Issue by clslgrnc** [webhintio/webhint.io#434]
As already mentioned in #400, your tool finds a few issues on your website:
https://sonarwhal.com/scanner/6d4b238b-d596-40fb-a366-ddbf31069612

Moreover, your pull request template has two dead links and a typo:
- https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests.html
- https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages
- relavant -> relevant

**Comment by molant** [comment]
@clslgrnc thanks!

There are a few that I was already aware of (cloudflare errors)  but some others I'm surprised (web.manifest for example).

**Comment by molant** [comment]
The new results are in https://sonarwhal.com/scanner/bd5bd893-fb87-4c63-a63d-ea3987d98d7c (8 errors)

There's something weird going on with the manifest because sonarwhal reports no compression and no caching when it's not true. If we access https://sonarwhal.com/static/site-b1a71cb190.webmanifest with the dev tools open I can see `br` compression. Maybe an issue with the jsdom connector?

Also not sure why the cache busting isn't picked up, it uses the same pattern as the other files so we will have to investigate.
