### ISSUE TITLE
sw.js is unminified in the live site

### ISSUE THREAD

**Issue by kshyju** [webhintio/webhint.io#443]
I ran sonarwhal on `https://sonarwhal.com/` and the new `js-minify-check` rule reports that we have an unminified js file in the page

<img width="416" alt="screen shot 2018-05-10 at 7 04 21 pm" src="https://user-images.githubusercontent.com/144469/39903076-37c04b2a-5486-11e8-8d0b-ee4aa25b71e1.png">
 
Is there a reason why we are not minifying it ?
https://sonarwhal.com/sw-reg.js

**Comment by molant** [comment]
Can't remember the specific reason. Maybe because it's from another project and we needed to keep the license? We need to review all the SW strategy (it's not minified nor cached), I'm not sure it is working correctly (I want online first but I seem to get old values, also I'm seeing issues with SRI from time to time). This is another thing to review.

Glad to see your rule works nicely!

**Comment by Malvoz** [comment]
Wrap the license in an "important comment" `/*! ... */`? I'm assuming the minifier that is used will respect those.

**Comment by molant** [comment]
It could be but I want to remember that there was something else. I think the problem was that we could end up registering multiple service workers if we minify them and change the names (`sw.js` --> `sw.1234.js`, `sw.5678.js`) and that would be a big problem. In any case, we've removed the service worker until we are sure to have the right strategy in place (I think we were discussing a network first approach but downloading all the hints documentation first) and we are not going to shoot ourselves in the foot.

I'm closing this issue but @Malvoz if you want to help with the service worker stuff we would appreciate!
