### ISSUE TITLE
Installing `node-zopfli` doesn't currently work [1]

### ISSUE THREAD

**Issue by alrra** [webhintio/webhint.io#448]
I've [switch to `node` LTS on `Travis CI`](https://github.com/sonarwhal/sonarwhal.com/commit/651c52e3ca6b28ecbe696664e1d5e417f09104bc) so that we can at least [build it (that also fails on latest node)](https://travis-ci.org/sonarwhal/sonarwhal.com/builds/384890645).

Ref: https://github.com/pierreinglebert/node-zopfli/issues/93

**Comment by molant** [comment]
Doesn't look like the package is going to be updated any time soon. I see a couple of alternatives:
- See if [node-zopfli-es](https://www.npmjs.com/package/node-zopfli-es) compiles on node 10 and can be a replacement
- Fork, use the code from https://github.com/chinhnguyen/node-zopfli (got from [this comment](https://github.com/pierreinglebert/node-zopfli/issues/98#issuecomment-430528249), automatically generate binaries for different platforms and publish them on GitHub instead of S3

Thoughts @webhintio/core?

**Comment by molant** [comment]
[There's a PR for this now](https://github.com/webhintio/webhint.io/pull/585)
