### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by ststimac** [webhintio/webhint.io#466]
Updating home page to reflect CLI & Scanner share equal promotion. 

@molant @alrra do either of you have a photo of the whiteboard where we outlined the sections?

**Comment by molant** [comment]
I thought you took one 😔

IIRC it was:

1. the header with cli and online results
1. Why use our tool. What we have right now with text aligned to the left and another alternative was in 3 rows with the images alternating from one side to the other
1. The input form for the online scanner
1. Cli section
1. Links to documentation similar to what we have now

**Comment by ststimac** [comment]
![screenshot](https://user-images.githubusercontent.com/18073131/42705523-72478dec-8688-11e8-9a37-d07120655e71.png)

currently trying to get a CLI screenshot for the top

**Comment by molant** [comment]
@ststimac wait until @alrra publishes the new version for the CLI screenshot (hopefully today).

**Comment by molant** [comment]
@ststimac can you do a quick mock up with the side by side option for the "why use webhint?" section where you have the text in one side and the image in the other alternating?

**Comment by ststimac** [comment]
![whyusewebhint](https://user-images.githubusercontent.com/18073131/42709908-f331f9de-8696-11e8-9057-006717f1da01.png)

**Comment by ststimac** [comment]
@molant is there a preference? (see above screenshot)

**Comment by molant** [comment]
I like where this is going. A few comments:

General
- Some buttons have `>` at the end and others don't
- Some buttons have no rounded corners (scanner), others just a bit the corners (header) and others are more rounded ("why use sonarwhal"). Shouldn't we try to normalize them?
- How do you feel about increasing a bit the regular font size? The computed size seems to be 16px, maybe 17px?
- The line spacing seems smaller in "why use sonarwhal" paragraphs and the other sections

Header
- I really like the new icons for the CLI and the online scanner
- We can keep the old logo. Nellie is staying so I don't see why we should remove it from the top left

Why use sonarwhal?
- It should be webhint
- The 3 columns in this section aren't aligned with the columns in the links section in the bottom

Use the online scanner
- The online scanner button doesn't have rounded borders, is this intentional?
- With the new Sherlock illustration I think we have too many illustrations that look relatively similar. Some ideas but open to anything:
  - Give a bit more depth to Nellie. Octocat, wombat, etc. all have some shadows
  - Change what she's doing. The wombat in [npm's](https://npmjs.com) page is a great example where he's doing lots of things (moving packages, climbing a mountain, high fiving). We have Nellie doing different things but it's more about the accessories she's wearing.
  - Remove the illustrations in "why use sonarwhal" similar to https://reactjs.org/ and swap the sherlock with the Nellie working on the computer

Install the sonarwhal CLI on your machine
- Should be webhint, maybe rename it to "Install webhint on your machine"
- The space between the header and the previous section is different than the previous sections

Great progress!

**Comment by ststimac** [comment]
@molant here is the updated homepage. If this looks good I will open a PR tomorrow morning. 

![sonarwhal-1](https://user-images.githubusercontent.com/18073131/43554862-ca989c16-95ab-11e8-9c6f-ecc16c06ab0c.PNG)

**Comment by ststimac** [comment]
@molant please ignore the line under the why use webhint illustrations. Photoshop artifact.

**Comment by molant** [comment]
I think I preferred the alignments of the icons in the hero from the previous version. Other than that it should be OK and I'd rather not wait any longer.

**Comment by ststimac** [comment]
![s-space-between](https://user-images.githubusercontent.com/18073131/43601371-da83b994-9641-11e8-9dca-b7baa89d3265.PNG)

I tried different values for spacing the icons. Trying to keep the right icon aligned all the way to the right creates a massive gap depending on your screen size. The current code/alignment works out so that the two icons stay spaced evenly no matter the screen size and that looks much better,

**Comment by ststimac** [comment]
It's now centered. I've opened a PR.
