### ISSUE TITLE
HTML formater output is broken when printing

### ISSUE THREAD

**Issue by DanielRuf** [webhintio/webhint.io#588]
The print version of a result looks a bit broken.
[webhint.pdf](https://github.com/webhintio/webhint.io/files/2713598/webhint.pdf)

**Comment by molant** [comment]
@ststimac want to take a look at this after the break?

**Comment by ststimac** [comment]
Just doing a quick pass, the way the summary column next to the results is implemented in responsive mode seems to be interefering with being able to print out results but I haven't been able to pinpoint exactly what it is.

**Comment by ststimac** [comment]
@molant this is going to to need to be created into an epic for next sprint. There's a cascade (pun intentional 😁) of issues that need to be fixed. 

HTML Formatter (formatter and scan results page on webhint.io) are broken due to something with the way position: fixed; and the other CSS properties are written for the rules-categories class. The positioning calc is partly to blame as well.  It's causing a total layout block of the scan results content.

The CSS is going to need to be rewritten and reworked and that will affect the mobile category menu/list implementation: 

- Mobile category menu needs to be updated anyway because it's not accessible via keyboard and there is no way to close or exit the menu. 
- Melanie has some code from a separate project that will keep the functionality we have for the categories menu on a mobile screen the same + is accessible. 

The mobile category menu/list button is broken in the HTML Formatter (but not on the website). "jump to category" doesn't open the menu like it does on the normal website, which causes the experience to feel broken even if HTML formatter results gathered from the CLI aren't meant to be viewed on mobile.

**Comment by molant** [comment]
What if we use [`@media print`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Examples)?
We could have a separate stylesheet just for printing that makes more sense?

**Comment by DanielRuf** [comment]
> What if we use @media print?

Which us recommended.

Media (print) rules gave a higher priority than the other rules.

**Comment by DanielRuf** [comment]
> What if we use @media print?

Which us recommended.

Media (print) rules have a higher priority than the other rules.

**Comment by DanielRuf** [comment]
Or move the other to media screen.

**Comment by ststimac** [comment]
@molant we can use `@media print` but things will still be broken on the website in terms of accessibility. We can rework the HTML Formatter layout, so should I open another issue for the scan results page & the accessibility issue?

**Comment by molant** [comment]
> should I open another issue for the scan results page & the accessibility issue?

Yes, let's do it as a separate task. Thanks!

**Comment by ststimac** [comment]
There is a PR open for this issue over in the hint repo: https://github.com/webhintio/hint/pull/1937
