### ISSUE TITLE
Rework homepage content to include end-to-end developer experience

### ISSUE THREAD

**Issue by antross** [webhintio/webhint.io#764]

**Comment by hxlnt** [comment]
See below for proposed homepage content. This reuses some existing content but adds a brief end-to-end developer story for development, debugging, and deployment. It now features the browser extension and VS Code extensions more prominently.

Please provide feedback in the comments! I didn't make a PR because I think we'll want to do some design and graphics updates in tandem with this.

---

>  **webhint is a customizable linting tool that helps you improve your site's accessibility, speed, cross-browser compatibility, and more by checking your code for best practices and common errors.**

# Hints to help you throughout the web development cycle

## Develop
Use the [webhint VS Code extension](https://marketplace.visualstudio.com/items?itemName=webhint.vscode-webhint) to get real-time feedback in your IDE as you write code for the web.

## Debug
The [webhint browser extension](https://webhint.io/docs/user-guide/extensions/extension-browser/) lets you scan a site from within your browser's DevTools.

## Deliver
Use the [webhint CLI](https://webhint.io/docs/user-guide/) in your CI/CD pipeline to ensure your site is accessible and compatible before it goes live.

# Try it
> Not sure what you want to configure the CLI to check? Use the online scanner for a pre-configured set of rule checks to cover the basics. [Type your URL here] [RUN SCAN]


# Make it your own

## Customize
Every site is different. webhint adapts its feedback when you give it more information: [ignore 3rd-party code](https://webhint.io/docs/user-guide/configuring-webhint/ignoring-domains/), [prioritize your users' browsers](https://webhint.io/docs/user-guide/configuring-webhint/browser-context/), and control the results with minimal setup.

## Create
With the help of our [contributor guide](https://webhint.io/docs/contributor-guide/), you can [create new hints](https://webhint.io/docs/contributor-guide/how-to/hint/) to suit your needs.

## Contribute

webhint welcomes anyone who wants to make the web a better place. [Join us on GitHub](https://github.com/webhintio/hint) to file issues and feature requests, contribute code, and improve the documentation!

**Comment by molant** [comment]
I like where this is going, especially how you've framed the "Try it" part. Nicely done!

Don't know if we have to use webpack in all the steps (haven't look at what other projects do):

**Develop**

```diff
- Use the webhint VS Code extension to get real-time feedback in your IDE as you write code for the web.
+ Use the VS Code extension to get real-time feedback in your IDE when writing code.
```
**Debug**

```dif
- The webhint browser extension lets you scan a site from within your browser's DevTools.
+ The browser extension lets you scan a site from within your browser's DevTools.
```
**Deliver**

Not quite sure about "limiting" CI/CD to a11y and compat. What about:

```diff
- Use the webhint CLI in your CI/CD pipeline to ensure your site is accessible and compatible before it goes live.
+ Use the CLI in your CI/CD pipeline to ensure a more thorough analysis before it goes live.
```
Or maybe mention something about perf and such? It's at this moment that we should be capable of getting a lot of details if they are using a staging environment.

**Try it**

I'd like us to avoid "negativity" or imply that something is complicated. What about:

```diff
- Not sure what you want to configure the CLI to check? Use the online scanner for a pre-configured set of rule checks to cover the basics. [Type your URL here] [RUN SCAN]
+  Use the online scanner for a pre-configured set of rule checks to see what the tools is capable of and how your website is doing. [Type your URL here] [RUN SCAN]
```

**Customize**

Maybe add a link to the user guide at the end?

**Contribute** 

I think that what we really want is to encourage participating in any kind. What about changing the name to "Participate" and also mentioning that we are also available on gitter?

**Comment by hxlnt** [comment]
Thanks, Anton--great suggestions. I made the changes you recommended to the Develop, Debug, and Try It portions. I reworded the Deliver part a bit but kept the spirit of your change. As for the recommendations on the Customize and Contribute parts, I was actually imagining that the existing footer content from webhint.io would remain, and that captures the user guide, Gitter links, etc.

**Comment by hxlnt** [comment]
Per today's retro/sprint planning, it sounds like the overall structure for the homepage redesign is good to go, even if there is still some remaining wordsmithing to do. Shall we close this issue and say that the content is ready for @ststimac's design magic?

**Comment by molant** [comment]
SGTM!

________________________________

**Comment by molant** [comment]
I've updated #765 to reference this issue so @ststimac can work on those updates whenever she has the time.

**Comment by ststimac** [comment]
To clarify, are we getting rid of the Online Scanner, Run webhint from the CLI and Documentation sections? Is this all the content we want on the home page?

**Comment by hxlnt** [comment]
I am proposing removing the "Try the online scanner" and "Get started with the CLI" portions at the top. The "Use the online scanner" section will remain per the draft above. 

I'd like for the footer to stay as well. However, I am leaning toward removing the section above the footer ("User Guide"/"Contributor Guide"/"Hints").

There's a separate issue open for tweaking the navbar, as I think we want to keep it but may end up changing it up a bit.

Open to feedback on all those plans!

**Comment by ststimac** [comment]
One more question @hxlnt, do we not have a heading for the very top hero section? Is it just diving into the description of what webhint is?

**Comment by hxlnt** [comment]
Yes, the hero text is in my draft above the A-head. I think it's the same text as before but without the special callouts for the scanner and CLI. Maybe we want to replace those with a more generic illo?
