### ISSUE TITLE
Consider delete staging during build.

### ISSUE THREAD

**Issue by sarvaje** [webhintio/webhint.io#783]
Yesterday (08/14/2019) we have a problem in staging that was resolve only after delete all the files from staging.

If this happens again, we should consider (if it is possible) force a deletion of the existing content in staging before deploy.

**Comment by antross** [comment]
Chatting with @hxlnt, she suggested this may have been due to stale state in the `node_modules` folder. Even though we were updating `package-lock.json`, `npm` may have already had some empty folders for certain packages due to the previously corrupted state that it wasn't updating until they got deleted.

Regardless, still a good thing to consider the delete step - especially if we see this again.
