### ISSUE TITLE
Fix `Clear-Site-Data` config issue

### ISSUE THREAD

**Issue by Malvoz** [webhintio/webhint.io#855]
### The issue:

![csd-header](https://user-images.githubusercontent.com/26493779/67881953-bc2ca800-fb41-11e9-99bb-8039ee0b6cef.png)

### The solution:

The [`Clear-Site-Data` HTTP header's](https://w3c.github.io/webappsec-clear-site-data/#header) values "_MUST comply with the quoted-string grammar_", as defined in https://tools.ietf.org/html/rfc7230#section-3.2.6.

```diff
- Clear-Site-Data: storage
+ Clear-Site-Data: "storage"
```

I would PR (to fix in [web.config](https://github.com/webhintio/webhint.io/blob/master/web.config)), but I've never used IIS and I'm not set up to test it.

**Comment by Malvoz** [comment]
Perhaps it could be useful with `hint-clear-site-data`? I had forgotten that I opened https://github.com/webhintio/hint/issues/2719, maybe merge with that for a new hint?

**Comment by molant** [comment]
We can't keep up with all your request 😅

Hopefully we will have some cycles after the Severity and breaking changes to start creating hints again.

RE the `web.config` I believe the change should be in [this line](https://github.com/webhintio/webhint.io/blob/7ac46db609e80876eece731fd61dd74268ae2fcb/web.config#L97) to:

```diff
- <action type="Rewrite" value="storage" />
+ <action type="Rewrite" value="\"storage\"" />
```

We have an staging environment where things get published before going to production so if you want and have time you can do a PR and we'll 🤞
If something breaks really bad it will not get deployed 😊

Otherwise I'll try to do this sometime soon.

Thanks!
